#!/usr/bin/env zsh

usage() {
    echo "Usage: $0 <key> [-n namespace]"
    echo "  - key: The key to search for in pod names."
    echo "  -n namespace: The Kubernetes namespace to search in (default: production)."
}

# Default values
local namespace="production"
local key="$1"

# Check for namespace flag
if [[ "$2" == "-n" ]] && [[ -n "$3" ]]; then
    namespace="$3"
elif [[ -n "$2" ]]; then
    usage
    return 1
fi

# Find the pod names based on the key
local pod_names=($(kubectl get pod -n "$namespace" | grep "$key" | awk '{print $1}'))

if [[ ${#pod_names[@]} -eq 0 ]]; then
    echo "No pods found with key: $key in namespace: $namespace"
    return 1
fi

# Pass the count of pod_names to AppleScript
local pod_count=${#pod_names[@]}

osascript <<EOF
tell application "iTerm"
  tell current window
    tell current session
      write text "kubectl logs -n '$namespace' -f '${pod_names[1]}' | jq"
      if $pod_count > 1 then
        split vertically with default profile
        delay 1
      end if
    end tell
    if $pod_count > 1 then
      tell last session of current tab
        write text "kubectl logs -n '$namespace' -f '${pod_names[2]}' | jq"
      end tell
    end if
  end tell
end tell
EOF

